### PR TITLE
Allow bare services to use $ref (and thus $call and $path)

### PR DESCRIPTION
**Pull request by djerius**

### CODE REVIEW

**Comment by preaction** [comment]
This a great idea, thanks!

**Comment by djerius** [comment]
Thanks! I believe this also closes #69.

**Comment by XSven** [comment]
Note that the new test script _t/service/ref.t_ requires at least perl 5.14 because it uses the `package NAMESPACE BLOCK;` syntax. To keep the MIN_PERL_VERSION requirement the test script should be fixed! Please check the Testers Report for details.

**Comment by djerius** [comment]
> Note that the new test script _t/service/ref.t_ requires at least perl 5.14 because it uses the `package NAMESPACE BLOCK;` syntax. To keep the MIN_PERL_VERSION requirement the test script should be fixed! Please check the Testers Report for details.

The fix is simple.  See #84 

However, a build from scratch on a clean 5.10 runs into dependency build issues;

- Safe: https://rt.cpan.org/Public/Bug/Display.html?id=103852; downgrade version to 0.9909
- Data::DPath: requires Sub::Exporter and Test::Deep, both of which require Perl 5.12
  - downgrade Data::OptList to 0.113, Test::Deep to 1.130; Sub::Exporter to 0.987

To properly build against dependencies available on CPAN, it looks like Perl 5.12 should be the minimum.

**Comment by djerius** [comment]
> To properly build against dependencies available on CPAN, it looks like Perl 5.12 should be the minimum.

That's incorrect according the bug in Safe that I reference, which looks like it might be resolved on perl 5.18+.

**Comment by djerius** [comment]
With patch #84 applied, I've attempted to build Beam::Wire against freshly installed versions of Perl

- 5.12: fails because of Safe issue mentioned above
- 5.14: succeeds
- 5.16: succeeds
- 5.18: succeeds

**Pull request merged**
