### PR TITLE
Pod fixes and an arsenal of "fix the broken readme stuff"

### PR DESCRIPTION
**Pull request by kentfredric**
And you're probably going to find your recent query re: Exporter POD to P5P amusing when you see what commits  1 and 2 are, .... esp given they happened before that :D

### CODE REVIEW

**Comment by preaction** [comment]
Yeah, that link one's funny: Markdown does [title](url), POD does L<title|url>, so why the hell did I do L<url|title>?

**Comment by kentfredric** [comment]
Extra humour arrives when you describe 2 formatting schemes in a github comment, and both of them get nuked sufficient to be invisible.

**Comment by preaction** [comment]
Yeah... More proof I need more sleep ;)

**Comment by preaction** [comment]
Thanks!

**Pull request merged**
